class RankingsController < ApplicationController

  def home
    @users = User.all
  end

  def classement
    @users = User.all
  end

  def calendrier
  end

  def monclassement
    @users = [

      "Pierre.cllt \r\n\npierre.cllt\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Jeannot_frrd \r\n\njeannot_frrd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Cam_hua \r\n\ncam_hua\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Paul_frd__ \r\n\npaul_frd__\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Sarahglln \r\n\nsarahglln\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Albert_delecroi \r\n\nalbert_delecroi\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Mgx.brun \r\n\nmgx.brun\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Roger_louis2 \r\n\nroger_louis2\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Emtaraa \r\n\nemtaraa\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Guillaumedelatu \r\n\nguillaumedelatu\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Clement.fr \r\n\nclement.fr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Pierrefessy \r\n\npierrefessy\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Pastagax \r\n\npastagax\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Emeline_gx \r\n\nemeline_gx\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Pierre_flyn \r\n\npierre_flyn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Basile_faierier \r\n\nbasile_faierier\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Paul.fouche \r\n\npaul.fouche\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Charles_thms \r\n\ncharles_thms\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Quentinjacquemo \r\n\nquentinjacquemo\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Huguesmnl \r\n\nhuguesmnl\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Dbslouis \r\n\ndbslouis\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Tarikfassifihri \r\n\ntarikfassifihri\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Nicoloco.lmp \r\n\nnicoloco.lmp\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Louis_bagard \r\n\nlouis_bagard\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Baptiste.gint \r\n\nbaptiste.gint\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Ludoadt \r\n\nludoadt\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Lucas_maxime \r\n\nlucas_maxime\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Lucbsgn \r\n\nlucbsgn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Eloi.leduc \r\n\neloi.leduc\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Openitniall \r\n\nopenitniall\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Charlottedsd \r\n\ncharlottedsd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Benjamin.dauphi \r\n\nbenjamin.dauphi\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Aude_lepercq \r\n\naude_lepercq\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Art_vador \r\n\nart_vador\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Florobank \r\n\nflorobank\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Mariliapetrini \r\n\nmariliapetrini\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Nastia.perfect \r\n\nnastia.perfect\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Corentin.jm \r\n\ncorentin.jm\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Rom.sgr \r\n\nrom.sgr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Espacemontagne \r\n\nespacemontagne\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Louis.rey \r\n\nlouis.rey\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Lucas_rch_ \r\n\nlucas_rch_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Douniamejjaoui \r\n\ndouniamejjaoui\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Eliottmagrez \r\n\neliottmagrez\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Mathlabase \r\n\nmathlabase\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Gasp_eus \r\n\ngasp_eus\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Adele_rose \r\n\nadele_rose\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Arthur_tual \r\n\narthur_tual\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Nawfal.l \r\n\nnawfal.l\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Nawresarfa \r\n\nnawresarfa\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Edouard_vdh \r\n\nedouard_vdh\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Guaniw \r\n\nguaniw\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Medou_herv \r\n\nmedou_herv\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Martinpotel2 \r\n\nmartinpotel2\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "La_fauchax \r\n\nla_fauchax\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Borisiek \r\n\nborisiek\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Haussière > +2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 4 points",
      "Tomaubl \r\n\ntomaubl\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Nizarkacimi1 \r\n\nnizarkacimi1\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Gregrichard99 \r\n\ngregrichard99\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Armandin.o \r\n\narmandin.o\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Raphaelbd73 \r\n\nraphaelbd73\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Robmonate \r\n\nrobmonate\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Virgile_martin \r\n\nvirgile_martin\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Echauvire \r\n\nechauvire\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Guillemette2bf \r\n\nguillemette2bf\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Allandlm \r\n\nallandlm\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Frdtim \r\n\nfrdtim\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Louise_gz \r\n\nlouise_gz\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Reussirlesmaths \r\n\nreussirlesmaths\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Annesou1 \r\n\nannesou1\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Amaury_wr \r\n\namaury_wr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Tom_ame46 \r\n\ntom_ame46\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Julien.dvl \r\n\njulien.dvl\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Matthieuoung123 \r\n\nmatthieuoung123\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Viviencerles \r\n\nviviencerles\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Dom.compagnie \r\n\ndom.compagnie\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Remiltrd \r\n\nremiltrd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Alex.uie \r\n\nalex.uie\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Theopode \r\n\ntheopode\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Billel_trb \r\n\nbillel_trb\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Le.petitdormeur \r\n\nle.petitdormeur\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Gautier_heron \r\n\ngautier_heron\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Titiraff \r\n\ntitiraff\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Tomtom.hey \r\n\ntomtom.hey\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Corentinfsc \r\n\ncorentinfsc\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Ferdi__26 \r\n\nferdi__26\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Margaux.fnd \r\n\nmargaux.fnd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Laurinedahlem \r\n\nlaurinedahlem\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Arthur.dupless \r\n\narthur.dupless\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Victor_rx_ \r\n\nvictor_rx_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Lamelledslv \r\n\nlamelledslv\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Manonmellerin \r\n\nmanonmellerin\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Guiche_lorraine \r\n\nguiche_lorraine\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marineoft \r\n\nmarineoft\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Augustingrn \r\n\naugustingrn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Ambroisepaillar \r\n\nambroisepaillar\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Pimorelea \r\n\npimorelea\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Sachabrjtmn \r\n\nsachabrjtmn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Greg_mnl \r\n\ngreg_mnl\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Leopaul_ferr \r\n\nleopaul_ferr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Nico_heron \r\n\nnico_heron\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Arthurtsch \r\n\narthurtsch\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Elodiejnnrd \r\n\nelodiejnnrd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Arthurameline \r\n\narthurameline\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Albail56 \r\n\nalbail56\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "David.bruc.1 \r\n\ndavid.bruc.1\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Tanguybourhis \r\n\ntanguybourhis\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Gabriel_rhgy \r\n\ngabriel_rhgy\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Xavier.boyen \r\n\nxavier.boyen\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Imirato \r\n\nimirato\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Belen.stm \r\n\nbelen.stm\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Clairemarine_pr \r\n\nclairemarine_pr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Simsim_o_ \r\n\nsimsim_o_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Antoine_rfy \r\n\nantoine_rfy\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Henrivvs \r\n\nhenrivvs\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Hugogesta \r\n\nhugogesta\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Cha_monniaux \r\n\ncha_monniaux\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Isaure_mi \r\n\nisaure_mi\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Alexis_kermo \r\n\nalexis_kermo\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Nabilallouche \r\n\nnabilallouche\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Capucine_brrr \r\n\ncapucine_brrr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Leoblanchard_ \r\n\nleoblanchard_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Felix.thmas \r\n\nfelix.thmas\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marie.amc \r\n\nmarie.amc\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Hamzadams \r\n\nhamzadams\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marteing44 \r\n\nmarteing44\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Elisar_97 \r\n\nelisar_97\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Foulk_lib \r\n\nfoulk_lib\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Basilehaignere \r\n\nbasilehaignere\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Amandine_couf \r\n\namandine_couf\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Skameplay \r\n\nskameplay\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marie_brgde \r\n\nmarie_brgde\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Jasonfouasson \r\n\njasonfouasson\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Alexi_bd \r\n\nalexi_bd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Florie_leker \r\n\nflorie_leker\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Craazybush \r\n\ncraazybush\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Geoffroydplx \r\n\ngeoffroydplx\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Baptiste_antier \r\n\nbaptiste_antier\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Annaelle_wkn \r\n\nannaelle_wkn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Nazir____13 \r\n\nnazir____13\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "P.chevalierlevr \r\n\np.chevalierlevr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Maxime_jcqs \r\n\nmaxime_jcqs\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Clemence_lambrt \r\n\nclemence_lambrt\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Leopoldine_maig \r\n\nleopoldine_maig\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Celineeyy \r\n\ncelineeyy\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Drt_pierre \r\n\ndrt_pierre\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Louise.dharcour \r\n\nlouise.dharcour\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Cecechitl \r\n\ncecechitl\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Mathilde_rtr \r\n\nmathilde_rtr\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Qctintin \r\n\nqctintin\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Emma.bernard \r\n\nemma.bernard\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Francoisbrly \r\n\nfrancoisbrly\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "__manon.c \r\n\n__manon.c\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Bapt_slg \r\n\nbapt_slg\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Mauganst \r\n\nmauganst\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Camillouxe \r\n\ncamillouxe\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Albane__kenhec \r\n\nalbane__kenhec\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Montarnal.theo \r\n\nmontarnal.theo\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marc_puget \r\n\nmarc_puget\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Elisecron \r\n\nelisecron\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Tomm7d \r\n\ntomm7d\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Invest_tips \r\n\ninvest_tips\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Jessk.a23 \r\n\njessk.a23\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Antoine_sane \r\n\nantoine_sane\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Etiennephilipon \r\n\netiennephilipon\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marieclouvel \r\n\nmarieclouvel\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Antoinemoniermj \r\n\nantoinemoniermj\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Mathis_.rsn \r\n\nmathis_.rsn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Maelleals \r\n\nmaelleals\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Antoi_herry \r\n\nantoi_herry\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marine_cauv \r\n\nmarine_cauv\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Karam_khmml \r\n\nkaram_khmml\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Jules_texier \r\n\njules_texier\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Moyartlouis \r\n\nmoyartlouis\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Julesguyvarch \r\n\njulesguyvarch\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Manon.dpm \r\n\nmanon.dpm\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Nbgd_ \r\n\nnbgd_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Louis_greverie \r\n\nlouis_greverie\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Investineo \r\n\ninvestineo\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Erwantous \r\n\nerwantous\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Hugo.hrtl \r\n\nhugo.hrtl\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Romiki.ng \r\n\nromiki.ng\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Celia_da \r\n\ncelia_da\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Maiiriv_ \r\n\nmaiiriv_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Mathieu.steger \r\n\nmathieu.steger\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Longtrandinh \r\n\nlongtrandinh\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Phgthuw \r\n\nphgthuw\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Claire.lng_ \r\n\nclaire.lng_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Jublancd \r\n\njublancd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Celestinrbt \r\n\ncelestinrbt\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Quent_bus \r\n\nquent_bus\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Trading_union \r\n\ntrading_union\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Farid_cbn \r\n\nfarid_cbn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Clement_derouet \r\n\nclement_derouet\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Yannick.chn \r\n\nyannick.chn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Philippine_cls \r\n\nphilippine_cls\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Vicdecast \r\n\nvicdecast\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Paul_baboulet \r\n\npaul_baboulet\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Thibault_boutin \r\n\nthibault_boutin\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Guillaumestn \r\n\nguillaumestn\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "_arthurleb \r\n\n_arthurleb\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Adriengrd_ \r\n\nadriengrd_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Diekitoo \r\n\ndiekitoo\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Victoria_krtz \r\n\nvictoria_krtz\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Lenabourgeois \r\n\nlenabourgeois\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Justinerpc \r\n\njustinerpc\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Iesegfinance \r\n\niesegfinance\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Valentin_aubame \r\n\nvalentin_aubame\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Eely.l \r\n\neely.l\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "_seeebb \r\n\n_seeebb\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Gabmaget \r\n\ngabmaget\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Chzlpierre \r\n\nchzlpierre\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marieameliie_ \r\n\nmarieameliie_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Valentine.gaut \r\n\nvalentine.gaut\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marieklr64 \r\n\nmarieklr64\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Inesbouaoun \r\n\ninesbouaoun\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Charlotte.bcm \r\n\ncharlotte.bcm\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Moustapha.shb \r\n\nmoustapha.shb\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Philippine_baro \r\n\nphilippine_baro\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Margotlalande \r\n\nmargotlalande\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Jeannefarin_ \r\n\njeannefarin_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Elisaborde \r\n\nelisaborde\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Amelie_anger \r\n\namelie_anger\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Vwigniolle \r\n\nvwigniolle\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Gabrieltib \r\n\ngabrieltib\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Caeli.academy \r\n\ncaeli.academy\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Sanmartia_ \r\n\nsanmartia_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Margotchml \r\n\nmargotchml\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Satorri \r\n\nsatorri\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Raph_mouss \r\n\nraph_mouss\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Johann_plt \r\n\njohann_plt\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Lablmatuer \r\n\nlablmatuer\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Jade_du21 \r\n\njade_du21\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Elena_lujan \r\n\nelena_lujan\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "G.h0173 \r\n\ng.h0173\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTu n'as pas répondu 😔\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Niggazaky \r\n\nniggazaky\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Staiy.le \r\n\nstaiy.le\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Baissière < -2%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Djib.diallo \r\n\ndjib.diallo\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Solenelbrd \r\n\nsolenelbrd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Omarsentassy \r\n\nomarsentassy\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Grandence \r\n\ngrandence\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Mathis.clerc \r\n\nmathis.clerc\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Joffrey_vhp \r\n\njoffrey_vhp\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Marie___aml \r\n\nmarie___aml\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Rico_rchd \r\n\nrico_rchd\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Enorarone \r\n\nenorarone\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "_eliisou \r\n\n_eliisou\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Hugo.delamare_ \r\n\nhugo.delamare_\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",
      "Alex_copin \r\n\nalex_copin\r\n\nPari 1 sur Zara : \r\nPublié le 06/06 \r\nTa réponse était Stable -1,99 % à 1,99%\r\nLa bonne réponse était Haussière > +2%\r\nTu as 0 point",

    ]

    if params[:word]
      @users = @users.select { |user| user.include?(params[:word]) }
    end
  end
end
